{"uuid":"b371efd2-ec81-429e-92fb-5262228f4b6f","historyId":"d9bdf8dcb78f518ebcc5b6d486e984f1","status":"passed","statusDetails":null,"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855747,"name":"visit / -> 302: https://opensource-demo.orangehrmlive.com/web/index.php/auth/login","stop":1692138856918},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138856916,"name":"GET --- /web/index.php/core/i18n/messages","stop":1692138856916},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138856918,"name":"fixture (\"example\")","stop":1692138856919},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138857921,"name":"get :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138857933}],"attachments":[],"parameters":[],"start":1692138857163,"name":"get :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138857933},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138857933,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.get()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138857933}],"attachments":[],"parameters":[],"start":1692138856928,"name":"get function(){}","stop":1692138857934},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138857934,"name":"assert expected **<document>** to be **visible**","stop":1692138857934},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138858048,"name":"type Admin","stop":1692138858645},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138858701,"name":"get :nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138858798}],"attachments":[],"parameters":[],"start":1692138858645,"name":"get function(){}","stop":1692138858808},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138858807,"name":"assert expected **<document>** to be **visible**","stop":1692138858807},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138859468,"name":"get :nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138859487}],"attachments":[],"parameters":[],"start":1692138858898,"name":"type admin123","stop":1692138859487},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138859487,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.type()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138859487},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138859487,"name":"get .oxd-button","stop":1692138859501},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138859501,"name":"click","stop":1692138859792},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138859792,"name":"page load --waiting for new page to load--","stop":1692138859792}],"attachments":[],"parameters":[],"start":1692138856923,"name":"login (\"Admin\"; \"admin123\")","stop":1692138859792},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138859792,"name":"new url https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index","stop":1692138860845},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138860844,"name":"GET --- /web/index.php/core/i18n/messages","stop":1692138860844},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138860845,"name":"get function(){}","stop":1692138860845},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138861964,"name":"get .oxd-topbar-header-breadcrumb > .oxd-text","stop":1692138861986}],"attachments":[],"parameters":[],"start":1692138860845,"name":"contains Dashboard","stop":1692138861988},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138861986,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.contains()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138861986},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138861987,"name":"GET --- /web/index.php/api/v2/dashboard/employees/action-summary","stop":1692138861987},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138861987,"name":"GET --- /web/index.php/api/v2/dashboard/shortcuts","stop":1692138861987},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138861987,"name":"GET --- /web/index.php/api/v2/buzz/feed?limit=5&offset=0&sortOrder=DESC&sortField=share.createdAtUtc","stop":1692138861987},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138861988,"name":"GET --- /web/index.php/api/v2/dashboard/employees/subunit","stop":1692138861988},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138861988,"name":"GET --- /web/index.php/api/v2/dashboard/employees/locations","stop":1692138861988},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138861988,"name":"POST --- /web/index.php/events/push","stop":1692138861988},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138861988,"name":"contains Invalid credentials","stop":1692138862080},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"actual","value":":cy-contains(**'Invalid credentials'**), [type=**'submit'**][value~=**'Invalid credentials'**]"},{"name":"expected","value":":cy-contains('Invalid credentials'), [type='submit'][value~='Invalid credentials']"}],"start":1692138862073,"name":"assert expected **:cy-contains(**'Invalid credentials'**), [type=**'submit'**][value~=**'Invalid credentials'**]** not to exist in the DOM","stop":1692138862073},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138862080,"name":"url","stop":1692138862108},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"actual","value":"https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index"},{"name":"expected","value":"https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index"}],"start":1692138862108,"name":"assert expected **https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index** to equal **https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index**","stop":1692138862108}],"attachments":[],"parameters":[],"start":1692138855670,"name":"\"before each\" hook","stop":1692138862108},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138862429,"name":"get :nth-child(4) > .oxd-main-menu-item > .oxd-text","stop":1692138862521}],"attachments":[],"parameters":[],"start":1692138862273,"name":"get function(){}","stop":1692138862523},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138862523,"name":"assert expected **<document>** to be **visible**","stop":1692138862523},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138863552,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.click()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138866171},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866162,"name":"new url https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/7","stop":1692138866162},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866162,"name":"request","stop":1692138866162},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866162,"name":"get :nth-child(4) > .oxd-main-menu-item > .oxd-text","stop":1692138866162},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866163,"name":"GET --- /web/index.php/api/v2/pim/employees/7/personal-details","stop":1692138866163},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866168,"name":"GET --- /web/index.php/api/v2/pim/employees/7","stop":1692138866168},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866169,"name":"GET --- /web/index.php/api/v2/leave/workweek?model=indexed","stop":1692138866169},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866170,"name":"GET --- /web/index.php/api/v2/leave/workweek?model=indexed","stop":1692138866170},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866170,"name":"GET --- /web/index.php/api/v2/pim/employees/7/custom-fields?screen=personal","stop":1692138866170},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866170,"name":"GET --- /web/index.php/api/v2/pim/employees/7/screen/personal/attachments?limit=50&offset=0","stop":1692138866170},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866170,"name":"GET --- /web/index.php/api/v2/leave/holidays?fromDate=2023-01-01&toDate=2023-12-31","stop":1692138866170},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866171,"name":"GET --- /web/index.php/api/v2/leave/holidays?fromDate=2023-01-01&toDate=2023-12-31","stop":1692138866171}],"attachments":[],"parameters":[],"start":1692138862539,"name":"click","stop":1692138866171},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866171,"name":"page load --page loaded--","stop":1692138866171},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866171,"name":"url","stop":1692138866177},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"actual","value":"https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/7"},{"name":"expected","value":"https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/7"}],"start":1692138866177,"name":"assert expected **https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/7** to equal **https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/7**","stop":1692138866177},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866177,"name":"get function(){}","stop":1692138866227},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866223,"name":"assert expected **<document>** to have a length above **0**","stop":1692138866223},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866691,"name":"get :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-input","stop":1692138866711},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866798,"name":"get :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-input","stop":1692138866858}],"attachments":[],"parameters":[],"start":1692138866227,"name":"get function(){}","stop":1692138866861},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866860,"name":"assert expected **<document>** to be **visible**","stop":1692138866860},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138866860,"name":"GET --- /web/index.php/api/v2/pim/employees","stop":1692138866860},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138868020,"name":"get :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-input","stop":1692138868168}],"attachments":[],"parameters":[],"start":1692138866979,"name":"clear","stop":1692138868169},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138868169,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.clear()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138868169},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138868214,"name":"get :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-input","stop":1692138868286}],"attachments":[],"parameters":[],"start":1692138868169,"name":"get function(){}","stop":1692138868286},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138868286,"name":"assert expected **<document>** to be **visible**","stop":1692138868286},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138868988,"name":"get :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-input","stop":1692138869010}],"attachments":[],"parameters":[],"start":1692138868300,"name":"type 2019-10-05","stop":1692138869016},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138869015,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.type()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138869015},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138869060,"name":"get .orangehrm-card-container > .oxd-form > .oxd-form-actions > .oxd-button","stop":1692138869072}],"attachments":[],"parameters":[],"start":1692138869016,"name":"get function(){}","stop":1692138869074},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138869074,"name":"assert expected **<document>** to be **visible**","stop":1692138869074},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138869454,"name":"get .orangehrm-card-container > .oxd-form > .oxd-form-actions > .oxd-button","stop":1692138869532}],"attachments":[],"parameters":[],"start":1692138869098,"name":"click","stop":1692138869540},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138869540,"name":"PUT --- /web/index.php/api/v2/pim/employees/7/custom-fields","stop":1692138869540},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138869540,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.click()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138869540},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138869594,"name":"get :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-input","stop":1692138869792}],"attachments":[],"parameters":[],"start":1692138869540,"name":"get function(){}","stop":1692138869792},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138869792,"name":"assert expected **<document>** to have value **2019-10-05**, but the value was **''**","stop":1692138869792}],"attachments":[],"parameters":[],"labels":[{"name":"package","value":"cypress.integration.test-spec.js"},{"name":"suite","value":"Navigate to MyInfo and verify/update Date of Birth field"}],"links":[],"start":1692138855669,"name":"should verify and update DOB field","fullName":"should verify and update DOB field","stop":1692138869844}